### ISSUE TITLE
About ceramic antenna models

### ISSUE THREAD

**Issue by weekinro** [siderakb/nrf51-module#1]
Hello, may I ask which model of ceramic antenna is used

**Comment by ziteh** [comment]
Sorry for the very late reply

The antenna is `AN2051-245` from Rainsun Microwave Tech
However, the module was never actually produced

I guess I was busy with other things and didn't reply immediately, so I kept forgetting about it

please feel free to reopen it if needed : )

**Comment by weekinro** [comment]
thanks,bro
